name: rxs
description: A simple library for composing states inspired by the reactivity system of Solid.js.
version: 0.1.0
repository: https://github.com/gekkotadev/rxs.git

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  rxdart: ^0.27.7
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
